name: flutter_syntactic_sorter
description: A new Flutter application.
version: 1.1.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  rxdart: ^0.22.0
  sqflite: ^1.1.3
  flutter_bloc: ^0.21.0
  http: ^0.12.0
  audioplayers: ^0.7.8
  cupertino_icons: ^0.1.2
  tuple: ^1.0.2
  shared_preferences: ^0.5.1+2
  sprintf: ^4.0.2
  devicelocale: ^0.1.1
  image_picker: 0.4.12+1
  image: any
  flutter_tts: any

dev_dependencies:
  pedantic: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/sounds/
  - assets/images/utils/
  - assets/images/all/
  - assets/images/game_settings/
  - assets/images/game/
  - assets/images/splash/
  - assets/lang/
  - assets/syntactic-sorter.db